(function(){
  'use strict';
  const VERSION='60.6';
  const STORE='ete_diagnostico_atual';
  const DEFAULT_STATE={
    version:VERSION,
    settings:{discipline:'Língua Portuguesa', supabaseUrl:'', supabaseAnonKey:''},
    assessment:{id:null, savedSignature:'', discipline:'Língua Portuguesa', turma:'', tipo:'diagnostica', date:'', teacher:'', questions:[], descriptors:[], key:[], students:[], title:'Avaliação atual'},
    assessments:[], activeAssessmentId:null, bank:[], snapshots:[], selectedStudent:null, currentReport:''
  };
  const $=(s,r=document)=>r.querySelector(s);
  const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const safe=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const norm=v=>String(v??'').trim();
  const letter=v=>{const m=norm(v).toUpperCase().match(/[A-E]/); return m?m[0]:''};
  const desc=v=>{const m=norm(v).toUpperCase().match(/D\s*0*([0-9]{1,2})/); return m?'D'+parseInt(m[1],10):''};
  const pct=(a,b)=>b?Math.round((a/b)*1000)/10:0;
  const performanceLevel=(percent, discipline='')=>{
    const p=Number(percent)||0;
    let label, cls, description;
    if(p<25){label='Elementar I'; cls='level-e1'; description='Grave defasagem. O estudante ainda não domina competências fundamentais da avaliação e precisa de recomposição imediata.';}
    else if(p<50){label='Elementar II'; cls='level-e2'; description='Desempenho insuficiente. O estudante reconhece estruturas simples, mas apresenta lacunas relevantes nas habilidades avaliadas.';}
    else if(p<75){label='Básico'; cls='level-basic'; description='O mínimo esperado. O estudante demonstra domínio essencial, mas ainda precisa consolidar descritores específicos.';}
    else {label='Desejável'; cls='level-des'; description='Nível de excelência. O estudante demonstra domínio avançado e maior autonomia nas habilidades avaliadas.';}
    return {label, cls, description, percent:p};
  };
  const status=(el,msg,type='work')=>{const node=typeof el==='string'?$(el):el;if(node){node.className='statusbox '+(type==='ok'?'status-ok':type==='error'?'status-error':'status-work');node.innerHTML=msg;}};
  const download=(filename,content,type='text/plain;charset=utf-8')=>{const blob=new Blob([content],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
  const toTSV=(rows)=>rows.map(r=>r.map(v=>String(v??'').replace(/\t/g,' ').replace(/\n/g,' ')).join('\t')).join('\n');
  const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
  function load(){try{const raw=JSON.parse(localStorage.getItem(STORE)||'{}');const st={...structuredClone(DEFAULT_STATE),...raw};st.settings={...DEFAULT_STATE.settings,...(raw.settings||{})};st.assessment={...DEFAULT_STATE.assessment,...(raw.assessment||{})};st.assessments=Array.isArray(raw.assessments)?raw.assessments:[];if(st.assessment&&st.assessment.id&&!st.activeAssessmentId)st.activeAssessmentId=st.assessment.id;return st;}catch{return structuredClone(DEFAULT_STATE)}}
  const App={VERSION, STORE, state:load(), $, $$, safe, norm, letter, desc, pct, status, download, toTSV, uid,
    save(){this.state.version=VERSION;localStorage.setItem(STORE,JSON.stringify(this.state));this.setSaveStatus();},
    setSaveStatus(){const dt=new Date().toLocaleString('pt-BR'); $('#lastSave')&&( $('#lastSave').textContent='Último salvamento: '+dt); $('#saveStatus')&&($('#saveStatus').textContent='Salvamento automático ativo • V'+VERSION);},
    setAssessment(a){this.state.assessment={...this.state.assessment,...a}; this.state.assessment.discipline=$('#assessmentDiscipline')?.value||this.state.assessment.discipline||this.state.settings.discipline; this.saveAssessmentRecord(false); this.save(); this.renderAll();},
    metaSignature(meta=this.state.assessment){return [meta.turma,meta.discipline,meta.tipo,meta.date,meta.title].map(x=>norm(x).toLowerCase()).join('|');},
    assessmentLabel(a=this.state.assessment){const tipoMap={diagnostica:'Diagnóstica',recuperacao:'Recuperação',bimestral:'Bimestral',personalizada:'Personalizada',...Object.fromEntries(Array.from({length:10},(_,i)=>['simulado'+(i+1),'Simulado '+(i+1)]))};return `${a.turma||'Turma?'} • ${a.discipline||'Disciplina?'} • ${tipoMap[a.tipo]||a.tipo||'Tipo?'} • ${a.date||'Data?'}`;},
    isMetaComplete(meta=this.state.assessment){const issues=[]; if(!norm(meta.turma))issues.push('turma'); if(!norm(meta.discipline))issues.push('disciplina'); if(!norm(meta.tipo))issues.push('tipo'); if(!norm(meta.date))issues.push('data'); return {ok:!issues.length, issues};},
    isAssessmentActiveSaved(){const a=this.state.assessment||{};return !!(a.id&&this.state.activeAssessmentId===a.id&&this.state.assessments.some(x=>x.id===a.id));},
    saveAssessmentRecord(render=true){let a=this.state.assessment; if(!a.id)return false; const rec={...a, updatedAt:new Date().toISOString(), savedSignature:this.metaSignature(a)}; const i=this.state.assessments.findIndex(x=>x.id===a.id); if(i>=0)this.state.assessments[i]=rec; else this.state.assessments.unshift(rec); this.state.activeAssessmentId=a.id; this.state.assessment={...rec}; if(render)this.renderAssessmentManager(); return true;},
    saveAssessmentMeta(){this.syncMetaFromInputs(false); const metaCheck=this.isMetaComplete(); const box=$('#assessmentSaveStatus'); if(!metaCheck.ok){status(box,'Preencha antes de salvar: '+metaCheck.issues.join(', ')+'.','error'); this.updateImportLock(); return;}
      const sig=this.metaSignature(); const existing=this.state.assessments.find(x=>this.metaSignature(x)===sig); if(existing){this.state.assessment={...existing}; this.state.activeAssessmentId=existing.id; this.fillMetaInputs(); status(box,'Avaliação já existia e foi aberta: '+safe(this.assessmentLabel(existing))+'.','ok');}
      else {const old=this.state.assessment||{}; const keepData = old.id && old.savedSignature===sig; this.state.assessment={...DEFAULT_STATE.assessment,...old,id:old.id||uid(),savedSignature:sig,createdAt:old.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()}; if(!keepData && old.savedSignature && old.savedSignature!==sig){this.state.assessment.questions=[];this.state.assessment.descriptors=[];this.state.assessment.key=[];this.state.assessment.students=[];} this.state.activeAssessmentId=this.state.assessment.id; this.clearImportDraft(); this.saveAssessmentRecord(false); status(box,'Avaliação salva e importação liberada: '+safe(this.assessmentLabel())+'.','ok');}
      this.save(); this.updateImportLock(); this.renderAll();},
    startNewAssessment(){this.state.assessment={...structuredClone(DEFAULT_STATE.assessment), discipline:this.state.settings.discipline||'Língua Portuguesa', title:'Nova avaliação'}; this.state.activeAssessmentId=null; this.clearImportDraft(); this.fillMetaInputs(); this.save(); this.renderAll();},
    openAssessment(id){const rec=this.state.assessments.find(x=>x.id===id); if(!rec)return; this.clearImportDraft(); this.state.assessment={...rec}; this.state.activeAssessmentId=id; this.state.settings.discipline=rec.discipline||this.state.settings.discipline; this.fillMetaInputs(); this.save(); this.renderAll(); this.showView('diagnostico');},
    duplicateAssessmentStructure(id=this.state.activeAssessmentId){const src=this.state.assessments.find(x=>x.id===id)||this.state.assessment; if(!src||!(src.questions||[]).length){alert('Abra uma avaliação com questões, descritores e gabarito para duplicar a estrutura.');return;} const turma=prompt('Informe a nova turma para duplicar a estrutura:', src.turma||''); if(turma===null)return; const date=prompt('Informe a data da nova avaliação (AAAA-MM-DD):', src.date||new Date().toISOString().slice(0,10)); if(date===null)return; this.state.assessment={...structuredClone(DEFAULT_STATE.assessment), id:uid(), title:src.title||'Avaliação duplicada', turma:norm(turma), discipline:src.discipline, tipo:src.tipo, date:norm(date), teacher:src.teacher||'', questions:[...(src.questions||[])], descriptors:[...(src.descriptors||[])], key:[...(src.key||[])], students:[], createdAt:new Date().toISOString()}; this.state.assessment.savedSignature=this.metaSignature(); this.state.activeAssessmentId=this.state.assessment.id; this.clearImportDraft(); this.saveAssessmentRecord(false); this.fillMetaInputs(); this.save(); this.renderAll(); this.showView('importar');},
    renderAssessmentManager(){const a=this.state.assessment; const box=$('#activeAssessmentBox'); if(box){if(this.isAssessmentActiveSaved())box.className='statusbox status-ok', box.innerHTML=`<b>Avaliação ativa salva</b><br>${safe(this.assessmentLabel())}<br><small>${(a.questions||[]).length} questões • ${(a.students||[]).length} alunos • ${safe(a.teacher||'Professor não informado')}</small>`; else box.className='statusbox status-work', box.innerHTML='Nenhuma avaliação ativa. Preencha os campos e clique em <b>Salvar avaliação</b> para liberar upload.';} const hist=$('#assessmentHistory'); if(hist){const list=this.state.assessments||[];hist.innerHTML=list.length?list.map(rec=>`<div class="assessment-item ${rec.id===this.state.activeAssessmentId?'active':''}"><div><b>${safe(rec.title||'Avaliação')}</b><br><span>${safe(this.assessmentLabel(rec))}</span><br><small>${(rec.questions||[]).length} questões • ${(rec.students||[]).length} alunos • ${new Date(rec.updatedAt||rec.createdAt||Date.now()).toLocaleString('pt-BR')}</small></div><div class="assessment-actions"><button class="smallBtn" data-open-assessment="${rec.id}">Abrir</button><button class="smallBtn secondary" data-dup-assessment="${rec.id}">Duplicar estrutura</button></div></div>`).join(''):'<p class="hint">Nenhuma avaliação salva ainda.</p>'; hist.querySelectorAll('[data-open-assessment]').forEach(b=>b.onclick=()=>this.openAssessment(b.dataset.openAssessment)); hist.querySelectorAll('[data-dup-assessment]').forEach(b=>b.onclick=()=>this.duplicateAssessmentStructure(b.dataset.dupAssessment));} this.updateImportLock();},
    updateImportLock(){const unlocked=this.isAssessmentActiveSaved(); ['fileInput','extractFile','loadExample','pdfOnlyInput','readPdfOnly','pasteData','validateData','validateDataGate','confirmImport'].forEach(id=>{const el=$('#'+id); if(el)el.disabled=!unlocked || (id==='confirmImport' && !window.Importacao?.pending);}); const ex=$('#extractStatus'); if(ex&&!unlocked) status(ex,'Salve uma avaliação antes de importar dados.','work'); return unlocked;},
    clearImportDraft(){if(window.Importacao)window.Importacao.pending=null; const f=$('#fileInput'); if(f)f.value=''; const pdf=$('#pdfOnlyInput'); if(pdf)pdf.value=''; const paste=$('#pasteData'); if(paste)paste.value=''; const prev=$('#previewImport'); if(prev)prev.innerHTML=''; const vr=$('#validationResult'); if(vr)vr.innerHTML=''; const gate=$('#importGate'); if(gate)status(gate,'Aguardando importação ou validação.','work'); const confirm=$('#confirmImport'); if(confirm)confirm.disabled=true;},
    getResults(){return window.Diagnostico?.compute(this.state.assessment)||{students:[],items:[],descriptorStats:[],summary:{nStudents:0,nQuestions:0,avg:0}}},
    renderAll(){window.Diagnostico?.render(); window.Relatorios?.renderCoord(); window.BancoQuestoes?.render(); window.Intervencoes?.render?.(); window.TurmasETE?.render?.(); window.Evolucao?.render?.(); this.renderSelects(); this.renderDescriptors(); this.renderQuestionMap(); this.renderChangelog(); this.renderWizard(); this.renderAssessmentManager();},
    renderSelects(){const students=this.state.assessment.students||[]; ['#mapStudent','#sheetStudent','#reportStudent'].forEach(sel=>{const e=$(sel); if(!e)return; const cur=e.value; e.innerHTML='<option value="">Selecione</option>'+students.map((s,i)=>`<option value="${i}">${safe(s.name)}</option>`).join(''); e.value=cur;});},
    renderQuestionMap(){const box=$('#questionMap'); if(!box)return; const a=this.state.assessment; if(!a.questions.length){box.innerHTML='<p class="hint">Nenhuma avaliação carregada.</p>';return;} box.innerHTML=a.questions.map((q,i)=>`<div class="question-card"><b>${safe(q||'Q'+(i+1))}</b><p>Descritor: <strong>${safe(a.descriptors[i]||'-')}</strong></p><p>Gabarito: <strong>${safe(a.key[i]||'-')}</strong></p></div>`).join('');},
    renderDescriptors(){const box=$('#descriptorList'); if(!box)return; const disc=$('#descriptorDiscipline')?.value||this.state.settings.discipline; const term=norm($('#descriptorSearch')?.value).toLowerCase(); const list=window.Descritores?.list(disc)||[]; const res=this.getResults(); const assoc={}; (this.state.assessment.descriptors||[]).forEach((d,i)=>{if(!d)return;(assoc[d]??=[]).push('Q'+(i+1));}); box.innerHTML=list.filter(d=>!term||JSON.stringify(d).toLowerCase().includes(term)).map(d=>`<details class="desc"><summary>${safe(d.codigo)} — ${safe(d.texto)}</summary><p><b>BNCC:</b> ${safe(d.bncc||'Não informada')}</p><p><b>Erros comuns:</b> ${safe(d.erros||'Leitura superficial, confusão conceitual ou estratégia inadequada.')}</p><p><b>Estratégias:</b> ${safe(d.estrategias||'Retomada guiada, modelagem de resolução e prática orientada.')}</p><p><b>Questões associadas nesta avaliação:</b> ${safe((assoc[d.codigo]||[]).join(', ')||'Nenhuma')}</p></details>`).join('')||'<p class="hint">Nenhum descritor encontrado.</p>';},
    renderChangelog(){const box=$('#changelogBox'); if(box) box.innerHTML='<h3>Versão 60.6</h3><ul><li>Correções de usabilidade e fluxo de importação.</li><li>IA pedagógica offline, sem API paga e sem custo mensal.</li><li>Sugestões automáticas para turma e aluno a partir dos descritores prioritários.</li><li>Importação e exportação de intervenções em CSV/JSON.</li><li>Integração das orientações com as fichas de recuperação.</li></ul>'; },
    isAssessmentValid(){const a=this.state.assessment||{};const issues=[];if(!(a.questions||[]).length)issues.push('nenhuma questão');if((a.descriptors||[]).length!==(a.questions||[]).length||((a.descriptors||[]).some(x=>!x)))issues.push('descritores ausentes');if((a.key||[]).length!==(a.questions||[]).length||((a.key||[]).some(x=>!x)))issues.push('gabarito incompleto');if(!(a.students||[]).length)issues.push('nenhum aluno');if((a.students||[]).some(s=>!s.name))issues.push('aluno sem nome');if((a.students||[]).some(s=>(s.answers||[]).length<(a.questions||[]).length))issues.push('respostas incompletas');const validCodes=window.Descritores?.validCodes?.(a.discipline||this.state.settings.discipline);if(validCodes){const invalid=[...new Set((a.descriptors||[]).filter(d=>d&&!validCodes.has(d)))];if(invalid.length)issues.push('descritores fora da matriz: '+invalid.join(', '));}return {ok:!issues.length,issues};},
    renderWizard(){const box=$('#wizardStatus');if(!box)return;const a=this.state.assessment;const valid=this.isAssessmentValid();const r=this.getResults();const steps=[['Importação',(a.questions||[]).length?'ok':'wait',`${(a.questions||[]).length||0} questões`],['Descritores',valid.issues.includes('descritores ausentes')?'bad':'ok',`${(a.descriptors||[]).filter(Boolean).length}/${(a.questions||[]).length||0}`],['Gabarito',valid.issues.includes('gabarito incompleto')?'bad':'ok',`${(a.key||[]).filter(Boolean).length}/${(a.questions||[]).length||0}`],['Alunos',(a.students||[]).length?'ok':'wait',`${(a.students||[]).length||0} alunos`],['Diagnóstico',r.summary.nStudents?'ok':'wait',r.summary.nStudents?`${r.summary.avg}% média`:'pendente'],['Relatórios',r.summary.nStudents?'ok':'wait',r.summary.nStudents?'prontos':'pendentes']];box.innerHTML=steps.map(([t,st,txt])=>`<div class="wizard-card ${st}"><b>${safe(t)}</b><span>${safe(txt)}</span></div>`).join('');const next=$('#wizardNext');if(next){if(!a.questions?.length)status(next,'Próxima ação: importe uma planilha Excel ou digite os dados manualmente.','work');else if(!valid.ok)status(next,'Ajuste a estrutura antes de analisar: '+valid.issues.join(', ')+'.','error');else if(!r.summary.nStudents)status(next,'Estrutura válida. Clique em Diagnóstico para analisar.','ok');else status(next,'Diagnóstico pronto. Gere relatórios, Mapa da Mina ou salve na nuvem.','ok');}},
    syncMetaFromInputs(checkChange=true){const a=this.state.assessment; const oldSig=this.metaSignature(a); const ids={title:'#assessmentTitle',turma:'#assessmentClass',tipo:'#assessmentType',date:'#assessmentDate',teacher:'#assessmentTeacher'}; if($(ids.title)) a.title=norm($(ids.title).value)||a.title; if($(ids.turma)) a.turma=norm($(ids.turma).value); if($('#assessmentDiscipline')) a.discipline=$('#assessmentDiscipline').value; if($(ids.tipo)) a.tipo=$(ids.tipo).value||a.tipo; if($(ids.date)) a.date=$(ids.date).value||a.date; if($(ids.teacher)) a.teacher=norm($(ids.teacher).value); const newSig=this.metaSignature(a); if(checkChange&&a.id&&a.savedSignature&&oldSig!==newSig){this.saveAssessmentRecord(false); this.state.assessment={...structuredClone(DEFAULT_STATE.assessment), title:a.title||'Nova avaliação', turma:a.turma, discipline:a.discipline, tipo:a.tipo, date:a.date, teacher:a.teacher}; this.state.activeAssessmentId=null; this.clearImportDraft(); status('#assessmentSaveStatus','Você alterou turma/disciplina/tipo/data. Salve para criar uma nova avaliação; a anterior foi preservada.','work');} this.updateImportLock();},
    fillMetaInputs(){const a=this.state.assessment; $('#assessmentTitle')&&($('#assessmentTitle').value=a.title||''); $('#assessmentClass')&&($('#assessmentClass').value=a.turma||''); $('#assessmentType')&&($('#assessmentType').value=a.tipo||'diagnostica'); $('#assessmentDate')&&($('#assessmentDate').value=a.date||''); $('#assessmentTeacher')&&($('#assessmentTeacher').value=a.teacher||''); $('#supabaseUrl')&&($('#supabaseUrl').value=this.state.settings.supabaseUrl||localStorage.getItem('ete_supabase_url')||''); $('#supabaseAnonKey')&&($('#supabaseAnonKey').value=this.state.settings.supabaseAnonKey||localStorage.getItem('ete_supabase_anon')||'');},
    bindBase(){
      $$('.nav').forEach(btn=>btn.onclick=()=>this.showView(btn.dataset.view)); $$('[data-go]').forEach(btn=>btn.onclick=()=>this.showView(btn.dataset.go));
      $('#openMenu')&&( $('#openMenu').onclick=()=>$('#sidebar')?.classList.add('open')); $('#closeMenu')&&( $('#closeMenu').onclick=()=>$('#sidebar')?.classList.remove('open'));
      $$('.tabBtn').forEach(btn=>btn.onclick=()=>{ $$('.tabBtn').forEach(b=>b.classList.remove('active')); $$('.tabPane').forEach(p=>p.classList.remove('active')); btn.classList.add('active'); $('#'+btn.dataset.tab)?.classList.add('active'); });
      $('#assessmentDiscipline')&&( $('#assessmentDiscipline').onchange=e=>{this.state.assessment.discipline=e.target.value;this.state.settings.discipline=e.target.value;$('#configDiscipline')&&($('#configDiscipline').value=e.target.value);this.syncMetaFromInputs(true);this.save();this.renderAll();});
      $('#configDiscipline')&&( $('#configDiscipline').onchange=e=>{this.state.settings.discipline=e.target.value;$('#assessmentDiscipline')&&($('#assessmentDiscipline').value=e.target.value);this.save();});
      ['assessmentTitle','assessmentClass','assessmentType','assessmentDate','assessmentTeacher'].forEach(id=>{const el=$('#'+id); if(el) el.onchange=el.oninput=()=>{this.syncMetaFromInputs(true); this.save(); this.renderAssessmentManager();};}); $('#saveAssessmentMeta')&&($('#saveAssessmentMeta').onclick=()=>this.saveAssessmentMeta()); $('#newAssessment')&&($('#newAssessment').onclick=()=>{if(confirm('Criar uma nova avaliação em branco? A avaliação atual salva será preservada.'))this.startNewAssessment();}); 
      $('#descriptorDiscipline')&&( $('#descriptorDiscipline').onchange=()=>this.renderDescriptors()); $('#descriptorSearch')&&( $('#descriptorSearch').oninput=()=>this.renderDescriptors());
      $('#wizardValidate')&&( $('#wizardValidate').onclick=()=>{this.showView('importar'); $('#validateData')?.click();}); $('#wizardAnalyze')&&( $('#wizardAnalyze').onclick=()=>{const v=this.isAssessmentValid(); if(!v.ok){alert('A estrutura ainda não está válida: '+v.issues.join(', ')); this.showView('importar');} else this.showView('diagnostico');});
      $('#studentSearch')&&( $('#studentSearch').oninput=()=>window.Diagnostico?.renderStudents());
      $('#clearAll')&&( $('#clearAll').onclick=()=>{if(confirm('Apagar todos os dados salvos neste navegador?')){localStorage.removeItem(STORE);location.reload();}});
    },
    showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id));$('#sidebar')?.classList.remove('open'); setTimeout(()=>scrollTo({top:0,behavior:'smooth'}),20);},
    init(){this.bindBase(); $('#assessmentDiscipline')&&($('#assessmentDiscipline').value=this.state.assessment.discipline||this.state.settings.discipline); $('#configDiscipline')&&($('#configDiscipline').value=this.state.settings.discipline); this.fillMetaInputs(); this.setSaveStatus(); this.updateImportLock(); this.renderAll();}
  };
  App.performanceLevel=performanceLevel;
  window.ETE=App; document.addEventListener('DOMContentLoaded',()=>App.init());
})();
